Repository p-adrian05/SZFM_2020_10_ErrorByNight_BigProject, pull requests merged in 2020-11, with the labels that each got.

#52 Szemand p2
  system_design.md
Labels: documentation

#58 Added Navigation bar
  webapp/src/main/resources/static/css/home.css
  webapp/src/main/resources/static/css/navbar.css
  webapp/src/main/resources/templates/main.html
Labels: Frontend

#59 Added register, login page and jpa configuration
  webapp/src/main/java/szfm/errorbynight/config/JpaConfig.java
  webapp/src/main/resources/static/css/login.css
  webapp/src/main/resources/static/css/registration.css
  webapp/src/main/resources/templates/login.html
  webapp/src/main/resources/templates/registration.html
Labels: Backend, Frontend

#60 Added RoleDao class
  webapp/src/main/java/szfm/errorbynight/repository/RoleDao.java
  webapp/src/main/java/szfm/errorbynight/repository/RoleDaoImpl.java
Labels: Backend, Database

#74 HomeController and Home page
  webapp/src/main/java/szfm/errorbynight/controller/HomeController.java
  webapp/src/main/resources/static/css/loggedIn.css
  webapp/src/main/resources/templates/home.html
  webapp/src/main/resources/templates/home.th.xml
  webapp/src/main/resources/templates/layouts/loggedInLayout.html
  webapp/src/main/resources/templates/layouts/loggedInLayout.th.xml
  webapp/src/main/resources/templates/layouts/main.html
  webapp/src/main/resources/templates/layouts/main.th.xml
  webapp/src/main/resources/templates/login.th.xml
Labels: Backend

#76 ForumService implementation
  webapp/src/main/java/szfm/errorbynight/controller/HomeController.java
  webapp/src/main/java/szfm/errorbynight/services/ForumService.java
  webapp/src/main/java/szfm/errorbynight/services/ForumServiceImpl.java
  webapp/src/main/java/szfm/errorbynight/util/ThemeStat.java
  webapp/src/main/java/szfm/errorbynight/validation/FieldsVerificationValidator.java
Labels: Backend

#83 PostController osztály létrehozása - Thymeleaf segítségével
  webapp/src/main/java/szfm/errorbynight/controller/PostController.java
  webapp/src/main/resources/templates/listPosts.th.xml
  webapp/src/main/resources/templates/postAnswerForm.th.xml
Labels: Backend

#84 TopicController osztály létrehozása - Thymeleaf segítségével
  webapp/src/main/java/szfm/errorbynight/controller/TopicController.java
  webapp/src/main/resources/templates/listTopics.th.xml
  webapp/src/main/resources/templates/newTopic.th.xml
Labels: Backend

#85 Posztok listázása oldal létrehozása
  webapp/src/main/resources/static/css/listPosts.css
  webapp/src/main/resources/templates/listPosts.html
Labels: Frontend

#86 navigation with js
  webapp/src/main/resources/static/js/pageNavigator.js
  webapp/src/main/resources/static/js/postList.js
Labels: Frontend

#88 Posztra válaszolás, új topik és topik listázása oldalak létrehozása
  webapp/src/main/resources/static/css/listTopic.css
  webapp/src/main/resources/static/css/newTopic.css
  webapp/src/main/resources/templates/listTopics.html
  webapp/src/main/resources/templates/newTopic.html
  webapp/src/main/resources/templates/postAnswerForm.html
Labels: Frontend

#103 Added MessageDetails entity class
  webapp/src/main/java/szfm/errorbynight/model/MessageDetails.java
Labels: Backend

#104 UserService - Üzenetek listázása
  webapp/src/main/java/szfm/errorbynight/services/UserServiceImpl.java
Labels: Backend

#105 Added Message entity class
  webapp/src/main/java/szfm/errorbynight/model/Message.java
Labels: Backend

#106 AccountController and UserService
  webapp/src/main/java/szfm/errorbynight/controller/AccountController.java
  webapp/src/main/java/szfm/errorbynight/repository/UserDao.java
  webapp/src/main/java/szfm/errorbynight/repository/UserDaoImpl.java
  webapp/src/main/java/szfm/errorbynight/services/UserService.java
  webapp/src/main/java/szfm/errorbynight/services/UserServiceImpl.java
  webapp/src/main/resources/static/js/privateMessage.js
  webapp/src/main/resources/templates/layouts/settings_layout.html
  webapp/src/main/resources/templates/layouts/settings_layout.th.xml
  webapp/src/main/resources/templates/listPrivateMessages.th.xml
  webapp/src/main/resources/templates/privateMessageForm.th.xml
  webapp/src/main/resources/templates/privateMessages.th.xml
  webapp/src/main/resources/templates/profile.th.xml
  webapp/src/main/resources/templates/userdata.th.xml
Labels: Backend

#107 Privát üzenetek, üzeneteküldés és user profil oldal létrehozása
  webapp/src/main/resources/static/css/privateMessages.css
  webapp/src/main/resources/static/css/settings_layout.css
  webapp/src/main/resources/static/css/userdata.css
  webapp/src/main/resources/templates/listPrivateMessages.html
  webapp/src/main/resources/templates/privateMessageForm.html
  webapp/src/main/resources/templates/privateMessages.html
  webapp/src/main/resources/templates/profile.html
Labels: Frontend

#114 Sprint4adrian
  webapp/src/main/java/szfm/errorbynight/controller/AccountController.java
  webapp/src/main/java/szfm/errorbynight/controller/HomeController.java
  webapp/src/main/java/szfm/errorbynight/controller/RegistrationController.java
  webapp/src/main/java/szfm/errorbynight/services/UserService.java
  webapp/src/main/java/szfm/errorbynight/services/UserServiceImpl.java
  webapp/src/main/java/szfm/errorbynight/util/InvalidUserToRegisterException.java
  webapp/user-images/default_profile_img.png
Labels: Backend

#117 UserDao tesztelés, ErrorPageController implementálása
  webapp/src/main/java/szfm/errorbynight/controller/ErrorPageController.java
  webapp/src/test/java/szfm/errorbynight/repository/UserDaoImplTest.java
Labels: Backend, Test

#122 RoleDao tesztelés
  webapp/src/test/java/szfm/errorbynight/repository/RoleDaoImplTest.java
Labels: Test
